#!/bin/bash
# =============================================================================
# HiveCFM Local Deployment Script
# One command to deploy everything from scratch
#
# Usage:
#   ./scripts/deploy-local.sh          # Fresh deploy
#   ./scripts/deploy-local.sh --reset  # Nuke everything and redeploy
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[HiveCFM]${NC} $1"; }
success() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# =============================================================================
# Pre-flight checks
# =============================================================================
log "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || error "Docker is not installed"
command -v docker compose >/dev/null 2>&1 || error "Docker Compose is not installed"
command -v openssl >/dev/null 2>&1 || error "openssl is not installed"

# Check Hub repo exists
if [ ! -f "../hivecfm-hub/Dockerfile" ]; then
  error "hivecfm-hub not found at ../hivecfm-hub/. Clone it next to hivecfm-core:
  cd .. && git clone https://istnetworksrnd@dev.azure.com/istnetworksrnd/HiveCFM/_git/hivecfm-hub"
fi

success "Prerequisites OK"

# =============================================================================
# Handle --reset flag
# =============================================================================
if [ "$1" = "--reset" ]; then
  warn "Resetting — this will DELETE ALL DATA"
  read -p "Are you sure? (y/N): " confirm
  if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
    log "Stopping all services and removing volumes..."
    docker compose down -v --remove-orphans 2>/dev/null || true
    success "Clean slate"
  else
    log "Aborted"
    exit 0
  fi
fi

# =============================================================================
# Generate .env if not exists
# =============================================================================
if [ ! -f ".env" ]; then
  log "Generating .env file with secure keys..."

  NEXTAUTH_SECRET=$(openssl rand -hex 32)
  ENCRYPTION_KEY=$(openssl rand -hex 32)

  cat > .env << EOF
# =============================================================================
# HiveCFM Local Environment Configuration
# Auto-generated by deploy-local.sh on $(date)
# =============================================================================

# ---- Database ----
DATABASE_URL=postgresql://postgres:postgres@postgres:5432/hivecfm?schema=public
POSTGRES_PASSWORD=postgres

# ---- Redis ----
REDIS_URL=redis://redis:6379

# ---- Application ----
WEBAPP_URL=http://localhost:3000
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENCRYPTION_KEY=$ENCRYPTION_KEY

# ---- Email (disabled for local) ----
EMAIL_VERIFICATION_DISABLED=1
PASSWORD_RESET_DISABLED=1

# ---- Enterprise Features ----
ENTERPRISE_LICENSE_KEY=hivecfm-enterprise-enabled
IS_FORMBRICKS_CLOUD=0
TELEMETRY_DISABLED=1
SIGNUP_DISABLED=0

# ---- MinIO Storage ----
S3_ACCESS_KEY=hivecfm
S3_SECRET_KEY=hivecfm-local-secret
S3_BUCKET_NAME=hivecfm-uploads
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=1
S3_INTERNAL_ENDPOINT=http://minio:9000
S3_ENDPOINT_URL=http://localhost:9000
MINIO_ROOT_USER=hivecfm
MINIO_ROOT_PASSWORD=hivecfm-local-secret

# ---- HiveCFM Hub ----
HIVECFM_HUB_URL=http://hivecfm-hub-api:8080
HIVECFM_HUB_API_KEY=hivecfm-hub-secret-key
EOF

  success ".env created with auto-generated keys"
else
  # Validate ENCRYPTION_KEY is proper hex
  CURRENT_KEY=$(grep "^ENCRYPTION_KEY=" .env | cut -d= -f2)
  if ! echo "$CURRENT_KEY" | grep -qE '^[0-9a-f]{64}$'; then
    warn "ENCRYPTION_KEY is not valid 64-char hex — regenerating..."
    NEW_KEY=$(openssl rand -hex 32)
    sed -i.bak "s|ENCRYPTION_KEY=.*|ENCRYPTION_KEY=$NEW_KEY|" .env && rm -f .env.bak
    success "ENCRYPTION_KEY fixed"
  fi
  success ".env exists and is valid"
fi

# =============================================================================
# Build and start everything
# =============================================================================
log "Building and starting all services..."
docker compose up -d --build 2>&1 | tail -20

# =============================================================================
# Wait for PostgreSQL to be healthy
# =============================================================================
log "Waiting for PostgreSQL..."
for i in $(seq 1 30); do
  if docker exec hivecfm-postgres pg_isready -U postgres -d hivecfm >/dev/null 2>&1; then
    success "PostgreSQL ready"
    break
  fi
  sleep 2
done

# =============================================================================
# Wait for Core to be ready
# =============================================================================
log "Waiting for HiveCFM Core (this may take 2-5 minutes on first run)..."
for i in $(seq 1 120); do
  STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000 2>/dev/null)
  if [ "$STATUS" = "200" ] || [ "$STATUS" = "302" ]; then
    success "HiveCFM Core ready"
    break
  fi
  if [ $((i % 15)) -eq 0 ]; then
    log "Still starting... ($i seconds)"
  fi
  sleep 2
done

if [ "$STATUS" != "200" ] && [ "$STATUS" != "302" ]; then
  warn "Core not ready after 4 minutes — check logs: docker compose logs -f hivecfm-core"
fi

# =============================================================================
# Check Hub
# =============================================================================
log "Checking Hub API..."
HUB_STATUS=$(curl -s http://localhost:8090/health 2>/dev/null)
if echo "$HUB_STATUS" | grep -q "OK\|ok"; then
  success "Hub API healthy"
else
  warn "Hub API not ready — check logs: docker logs hivecfm-hub-api"
fi

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  HiveCFM Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "  Services:"
echo "    HiveCFM Core    http://localhost:3000"
echo "    MinIO Console   http://localhost:9001"
echo "    Hub API         http://localhost:8090"
echo "    River UI        http://localhost:8091"
echo "    Superset        http://localhost:3002"
echo ""
echo "  Next steps:"
echo "    1. Open http://localhost:3000"
echo "    2. Create your admin account"
echo "    3. Create an organization (trial license auto-created)"
echo "    4. Start building surveys!"
echo ""
echo "  Commands:"
echo "    View logs:    docker compose logs -f hivecfm-core"
echo "    Stop:         docker compose down"
echo "    Reset:        ./scripts/deploy-local.sh --reset"
echo ""
